import type { AnalyticsRow } from "./types"

// Sample data shown only when SUPABASE_SERVICE_ROLE_KEY isn't configured
// (see lib/analytics/fetch.ts) — lets the Overview page be built and
// previewed (including every filter/chart) before the admin dashboard is
// wired up to production, without ever silently masking a real query
// failure once the key *is* set.
function row(partial: Partial<AnalyticsRow> & { id: string }): AnalyticsRow {
  return {
    surveyVersion: 1,
    createdAt: "2026-09-01T08:00:00.000Z",
    startedAt: "2026-09-01T07:50:00.000Z",
    durationSeconds: 600,
    durationMinutes: 10,
    year: "2",
    hostel: "parijat",
    earlyCommitmentDays: "3",
    breakfastFrequency: "most-days",
    branch: "A",
    attentionCheckPassed: true,
    hasArchetypeResult: true,
    primaryArchetype: "routine-keeper",
    secondaryArchetype: "sleep-saver",
    archetypeConfidence: "strong",
    ...partial,
  }
}

export const DUMMY_ANALYTICS_ROWS: AnalyticsRow[] = [
  row({
    id: "dummy-1",
    createdAt: "2026-08-28T07:40:00.000Z",
    durationSeconds: 711,
    durationMinutes: 11.85,
    hostel: "bakul",
    year: "1",
    earlyCommitmentDays: "4",
    breakfastFrequency: "almost-every-day",
    branch: "A",
    primaryArchetype: "routine-keeper",
    secondaryArchetype: "sleep-saver",
    archetypeConfidence: "strong",
  }),
  row({
    id: "dummy-2",
    createdAt: "2026-08-28T08:10:00.000Z",
    durationSeconds: 761,
    durationMinutes: 12.68,
    hostel: "parijat",
    year: "2",
    earlyCommitmentDays: "2",
    breakfastFrequency: "some-days",
    branch: "B",
    primaryArchetype: "schedule-juggler",
    secondaryArchetype: "sleep-saver",
    archetypeConfidence: "mixed",
  }),
  row({
    id: "dummy-3",
    createdAt: "2026-08-29T09:05:00.000Z",
    durationSeconds: 1157,
    durationMinutes: 19.29,
    hostel: "obh",
    year: "2",
    earlyCommitmentDays: "5+",
    breakfastFrequency: "rarely",
    branch: "C",
    attentionCheckPassed: false,
    primaryArchetype: "sleep-saver",
    secondaryArchetype: "alternative-forager",
    archetypeConfidence: "mixed",
  }),
  row({
    id: "dummy-4",
    createdAt: "2026-08-29T10:20:00.000Z",
    durationSeconds: 1243,
    durationMinutes: 20.72,
    hostel: "kadamba",
    year: "3",
    earlyCommitmentDays: "1",
    breakfastFrequency: "most-days",
    branch: "A",
    primaryArchetype: "schedule-juggler",
    secondaryArchetype: "meal-maximizer",
    archetypeConfidence: "strong",
  }),
  row({
    id: "dummy-5",
    createdAt: "2026-08-30T07:55:00.000Z",
    durationSeconds: 168,
    durationMinutes: 2.8,
    hostel: "parijat",
    year: "1",
    earlyCommitmentDays: "0",
    breakfastFrequency: "never",
    branch: "C",
    hasArchetypeResult: false,
    primaryArchetype: null,
    secondaryArchetype: null,
    archetypeConfidence: null,
  }),
  row({
    id: "dummy-6",
    createdAt: "2026-08-30T08:30:00.000Z",
    durationSeconds: 542,
    durationMinutes: 9.03,
    hostel: "bakul",
    year: "4",
    earlyCommitmentDays: "3",
    breakfastFrequency: "some-days",
    branch: "B",
    primaryArchetype: "flexible-switcher",
    secondaryArchetype: "alternative-forager",
    archetypeConfidence: "strong",
  }),
]
