import type { AnalyticsRow } from "./types"

// Sample data shown only when SUPABASE_SERVICE_ROLE_KEY isn't configured
// (see lib/analytics/fetch.ts) — lets the Overview page be built and
// previewed (including every filter/chart) before the admin dashboard is
// wired up to production, without ever silently masking a real query
// failure once the key *is* set.
function row(partial: Partial<AnalyticsRow> & { id: string }): AnalyticsRow {
  return {
    surveyVersion: 1,
    createdAt: "2026-09-01T08:00:00.000Z",
    startedAt: "2026-09-01T07:50:00.000Z",
    durationSeconds: 600,
    durationMinutes: 10,
    year: "2",
    hostel: "parijat",
    earlyCommitmentDays: "3",
    program: null,
    gender: null,
    sleepTimeWeekend: null,
    wakeTimeWeekend: null,
    beforeSleepActivities: [],
    beforeSleepMostTime: null,
    morningActivities: [],
    messDecision: null,
    messFoodQuality: null,
    messBreakfastTime: null,
    breakfastMoment: null,
    breakfastRoutineDuration: null,
    earlyClassRoutineChange: null,
    earlyClassRoutineChangeActions: [],
    unwantedMessActions: [],
    messConsistency: null,
    messChangeDeterminants: [],
    breakfastRoutineDescription: null,
    breakfastMotivationFactors: [],
    conditionalMessBreakfastTime: null,
    breakfastDecisionPoint: null,
    breakfastDayDifferentiators: [],
    breakfastAbsenceReason: null,
    breakfastAbsenceDecisionPoint: null,
    occasionalBreakfastFrequency: null,
    occasionalBreakfastDifferentiators: [],
    breakfastFrequencyChanged: null,
    weekendDifferentiators: [],
    previousNightAffectsBreakfast: null,
    previousNightFactors: [],
    influenceRatings: {},
    biggestInfluenceFactor: null,
    agreementRatings: {},
    mealValuePerception: null,
    breakfastImprovementOptions: [],
    semesterBreakfastChangeDescription: null,
    breakfastFrequencyChangeDescription: null,
    breakfastSystemChangeSuggestion: null,
    breakfastFrequency: "most-days",
    branch: "A",
    sleepTimeWeekday: "12am-1am",
    wakeTimeWeekday: "700-730am",
    earlyCommitmentBreakfastFrequency: "sometimes",
    noEarlyCommitmentBreakfastFrequency: "often",
    weekendBreakfastComparison: "about-the-same",
    semesterBreakfastChange: "about-the-same",
    breakfastPlanChangeFrequency: "rarely",
    breakfastPlanChangeActions: ["use-allotted"],
    missedBreakfastFrequency: "rarely",
    missedBreakfastReasons: ["woke-up-later"],
    breakfastPlannedButSkippedFrequency: null,
    breakfastUnplannedButWentFrequency: null,
    breakfastPlanChangeReasons: [],
    breakfastServedTimeActivity: null,
    unusedAllottedMealActions: [],
    nonBreakfastMealSource: ["eat-in-room"],
    nextFoodTime: "before-10am",
    nonBreakfastSpendingFrequency: "rarely",
    nonBreakfastSpendingAmount: "under-50",
    comparisonRatings: {
      comparisonEnergyLevel: "slightly-lower",
      comparisonConcentration: "slightly-lower",
      comparisonHunger: "slightly-higher",
    },
    attentionCheckPassed: true,
    hasArchetypeResult: true,
    primaryArchetype: "routine-keeper",
    secondaryArchetype: "sleep-saver",
    archetypeConfidence: "strong",
    ...partial,
  }
}

export const DUMMY_ANALYTICS_ROWS: AnalyticsRow[] = [
  row({
    id: "dummy-1",
    createdAt: "2026-08-28T07:40:00.000Z",
    durationSeconds: 711,
    durationMinutes: 11.85,
    hostel: "bakul",
    year: "1",
    earlyCommitmentDays: "4",
    breakfastFrequency: "almost-every-day",
    branch: "A",
    sleepTimeWeekday: "11pm-12am",
    wakeTimeWeekday: "before-630am",
    earlyCommitmentBreakfastFrequency: "almost-always",
    noEarlyCommitmentBreakfastFrequency: "almost-always",
    weekendBreakfastComparison: "about-the-same",
    semesterBreakfastChange: "about-the-same",
    breakfastPlanChangeFrequency: "never",
    breakfastPlanChangeActions: [],
    missedBreakfastFrequency: "never",
    missedBreakfastReasons: [],
    nonBreakfastMealSource: ["eat-in-room"],
    nextFoodTime: "before-10am",
    nonBreakfastSpendingFrequency: "never",
    nonBreakfastSpendingAmount: null,
    comparisonRatings: {},
    primaryArchetype: "routine-keeper",
    secondaryArchetype: "sleep-saver",
    archetypeConfidence: "strong",
  }),
  row({
    id: "dummy-2",
    createdAt: "2026-08-28T08:10:00.000Z",
    durationSeconds: 761,
    durationMinutes: 12.68,
    hostel: "parijat",
    year: "2",
    earlyCommitmentDays: "2",
    breakfastFrequency: "some-days",
    branch: "B",
    sleepTimeWeekday: "1am-2am",
    wakeTimeWeekday: "730-800am",
    earlyCommitmentBreakfastFrequency: "sometimes",
    noEarlyCommitmentBreakfastFrequency: "often",
    weekendBreakfastComparison: "more-often",
    semesterBreakfastChange: "less-often-now",
    breakfastPlanChangeFrequency: "sometimes",
    breakfastPlanChangeActions: ["exchange", "eat-elsewhere"],
    missedBreakfastFrequency: null,
    missedBreakfastReasons: [],
    breakfastPlannedButSkippedFrequency: "sometimes",
    breakfastUnplannedButWentFrequency: "rarely",
    breakfastPlanChangeReasons: [
      "woke-different-than-expected",
      "schedule-changed",
    ],
    nonBreakfastMealSource: ["buy-vc-canteen"],
    nextFoodTime: "10-11am",
    nonBreakfastSpendingFrequency: "sometimes",
    nonBreakfastSpendingAmount: "50-100",
    comparisonRatings: {
      comparisonEnergyLevel: "slightly-lower",
      comparisonConcentration: "about-the-same",
      comparisonHunger: "slightly-higher",
    },
    primaryArchetype: "schedule-juggler",
    secondaryArchetype: "sleep-saver",
    archetypeConfidence: "mixed",
  }),
  row({
    id: "dummy-3",
    createdAt: "2026-08-29T09:05:00.000Z",
    durationSeconds: 1157,
    durationMinutes: 19.29,
    hostel: "obh",
    year: "2",
    earlyCommitmentDays: "5+",
    breakfastFrequency: "rarely",
    branch: "C",
    sleepTimeWeekday: "after-3am",
    wakeTimeWeekday: "900-1000am",
    earlyCommitmentBreakfastFrequency: "rarely",
    noEarlyCommitmentBreakfastFrequency: "sometimes",
    weekendBreakfastComparison: "rarely-never-either",
    semesterBreakfastChange: "changed-back-and-forth",
    breakfastPlanChangeFrequency: "often",
    breakfastPlanChangeActions: ["leave-unused", "skip-breakfast"],
    missedBreakfastFrequency: null,
    missedBreakfastReasons: [],
    breakfastPlannedButSkippedFrequency: null,
    breakfastUnplannedButWentFrequency: null,
    breakfastPlanChangeReasons: [],
    breakfastServedTimeActivity: "sleeping",
    unusedAllottedMealActions: ["leave-unused", "not-sure"],
    nonBreakfastMealSource: ["wait-until-lunch"],
    nextFoodTime: "after-lunchtime",
    nonBreakfastSpendingFrequency: "often",
    nonBreakfastSpendingAmount: "50-100",
    comparisonRatings: {
      comparisonEnergyLevel: "much-lower",
      comparisonConcentration: "slightly-lower",
      comparisonHunger: "much-higher",
    },
    attentionCheckPassed: false,
    primaryArchetype: "sleep-saver",
    secondaryArchetype: "alternative-forager",
    archetypeConfidence: "mixed",
  }),
  row({
    id: "dummy-4",
    createdAt: "2026-08-29T10:20:00.000Z",
    durationSeconds: 1243,
    durationMinutes: 20.72,
    hostel: "kadamba",
    year: "3",
    earlyCommitmentDays: "1",
    breakfastFrequency: "most-days",
    branch: "A",
    sleepTimeWeekday: "12am-1am",
    wakeTimeWeekday: "700-730am",
    earlyCommitmentBreakfastFrequency: "sometimes",
    noEarlyCommitmentBreakfastFrequency: "often",
    weekendBreakfastComparison: "more-often",
    semesterBreakfastChange: "less-often-now",
    breakfastPlanChangeFrequency: "sometimes",
    breakfastPlanChangeActions: ["sell", "eat-elsewhere"],
    missedBreakfastFrequency: "sometimes",
    missedBreakfastReasons: ["earlier-commitment", "less-time"],
    nonBreakfastMealSource: ["buy-vc-canteen"],
    nextFoodTime: "10-11am",
    nonBreakfastSpendingFrequency: "sometimes",
    nonBreakfastSpendingAmount: "under-50",
    comparisonRatings: {
      comparisonEnergyLevel: "slightly-lower",
      comparisonConcentration: "slightly-lower",
      comparisonHunger: "slightly-higher",
    },
    primaryArchetype: "schedule-juggler",
    secondaryArchetype: "meal-maximizer",
    archetypeConfidence: "strong",
  }),
  row({
    id: "dummy-5",
    createdAt: "2026-08-30T07:55:00.000Z",
    durationSeconds: 168,
    durationMinutes: 2.8,
    hostel: "parijat",
    year: "1",
    earlyCommitmentDays: "0",
    breakfastFrequency: "never",
    branch: "C",
    sleepTimeWeekday: "no-consistent-time",
    wakeTimeWeekday: "no-consistent-time",
    earlyCommitmentBreakfastFrequency: "not-applicable",
    noEarlyCommitmentBreakfastFrequency: "never",
    weekendBreakfastComparison: "rarely-never-either",
    semesterBreakfastChange: "not-sure",
    breakfastPlanChangeFrequency: "almost-always",
    breakfastPlanChangeActions: ["skip-breakfast", "leave-unused"],
    missedBreakfastFrequency: null,
    missedBreakfastReasons: [],
    breakfastPlannedButSkippedFrequency: null,
    breakfastUnplannedButWentFrequency: null,
    breakfastPlanChangeReasons: [],
    breakfastServedTimeActivity: "getting-ready",
    unusedAllottedMealActions: ["sell", "exchange"],
    nonBreakfastMealSource: ["eat-elsewhere-campus"],
    nextFoodTime: "around-lunchtime",
    nonBreakfastSpendingFrequency: "almost-always",
    nonBreakfastSpendingAmount: "over-150",
    comparisonRatings: {},
    hasArchetypeResult: false,
    primaryArchetype: null,
    secondaryArchetype: null,
    archetypeConfidence: null,
  }),
  row({
    id: "dummy-6",
    createdAt: "2026-08-30T08:30:00.000Z",
    durationSeconds: 542,
    durationMinutes: 9.03,
    hostel: "bakul",
    year: "4",
    earlyCommitmentDays: "3",
    breakfastFrequency: "some-days",
    branch: "B",
    sleepTimeWeekday: "11pm-12am",
    wakeTimeWeekday: "800-830am",
    earlyCommitmentBreakfastFrequency: "often",
    noEarlyCommitmentBreakfastFrequency: "often",
    weekendBreakfastComparison: "about-the-same",
    semesterBreakfastChange: "more-often-now",
    breakfastPlanChangeFrequency: "rarely",
    breakfastPlanChangeActions: ["use-allotted"],
    missedBreakfastFrequency: null,
    missedBreakfastReasons: [],
    breakfastPlannedButSkippedFrequency: "rarely",
    breakfastUnplannedButWentFrequency: "sometimes",
    breakfastPlanChangeReasons: ["menu", "friends-plans"],
    nonBreakfastMealSource: ["eat-in-room"],
    nextFoodTime: "before-10am",
    nonBreakfastSpendingFrequency: "rarely",
    nonBreakfastSpendingAmount: "under-50",
    comparisonRatings: {
      comparisonEnergyLevel: "about-the-same",
      comparisonConcentration: "slightly-lower",
      comparisonHunger: "slightly-higher",
    },
    primaryArchetype: "flexible-switcher",
    secondaryArchetype: "alternative-forager",
    archetypeConfidence: "strong",
  }),
]
